version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
